version: '3'

services:
  nats-server:
    image: nats:alpine3.19
    ports:
      - '8222:8222'

  client-gateway:
    build: ./client-gateway
    ports:
      - ${CLIENT_GATEWAY_PORT}:3000
    volumes:
      - ./client-gateway/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3000
      - NATS_SERVERS=nats://nats-server:4222

  auth-ms:
    depends_on:
      - auth-db
    build: ./auth-ms
    volumes:
      - ./auth-ms/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3004
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${AUTH_DATABASE_URL}
      - JWT_SECRET=${JWT_SECRET}

  auth-db:
    container_name: auth_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./auth-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${AUTH_POSTGRES_USER}
      - POSTGRES_PASSWORD=${AUTH_POSTGRES_PASSWORD}
      - POSTGRES_DB=${AUTH_POSTGRES_DB}

  products-ms:
    build: ./products-ms
    volumes:
      - ./products-ms/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3001
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=file:./dev.db
  orders-ms:
    depends_on:
      - orders-db
    build: ./orders-ms
    volumes:
      - ./orders-ms/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - PORT=3002
      - NATS_SERVERS=nats://nats-server:4222
      - DATABASE_URL=${ORDERS_DATABASE_URL}

  orders-db:
    container_name: orders_database
    image: postgres:16.2
    restart: always
    volumes:
      - ./orders-ms/postgres:/var/lib/postgresql/data
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${ORDERS_POSTGRES_USER}
      - POSTGRES_PASSWORD=${ORDERS_POSTGRES_PASSWORD}
      - POSTGRES_DB=${ORDERS_POSTGRES_DB}

  # # =======================================
  # # Payments Microservice
  # # =======================================

  payments-ms:
    build: ./payments-ms
    ports:
      - ${PAYMENTS_PORT}:${PAYMENTS_PORT}
    volumes:
      - ./payments-ms/src:/usr/src/app/src
    command: yarn start:dev
    environment:
      - NATS_SERVERS=nats://nats-server:4222
      - PORT=${PAYMENTS_PORT}
      - STRIPE_SECRET=${PAYMENTS_STRIPE_SECRET}
      - STRIPE_SUCCESS_URL=${PAYMENTS_STRIPE_SUCCESS_URL}
      - STRIPE_CANCEL_URL=${PAYMENTS_STRIPE_CANCEL_URL}
      - STRIPE_ENDPOINT_SECRET=${PAYMENTS_STRIPE_ENDPOINT_SECRET}
